### ISSUE TITLE
Getting the below error for tamil input image

### ISSUE THREAD

**Issue by tshrinivasan** [suddharshan/slicing-one-image-into-many-parts#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/PIL/JpegImagePlugin.py", line 621, in _save
    rawmode = RAWMODE[im.mode]
KeyError: 'RGBA'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "image slicing.py", line 26, in <module>
    im1.save(str(b)+'.jpg')
  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 1950, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/dist-packages/PIL/JpegImagePlugin.py", line 623, in _save
    raise IOError("cannot write mode %s as JPEG" % im.mode)
OSError: cannot write mode RGBA as JPEG

**Comment by tshrinivasan** [comment]
![tam](https://user-images.githubusercontent.com/1268536/79132824-97af4a00-7dc8-11ea-9042-1484efb55610.png)
